mesecons_materials/init.lua
Moretree and Ethereal mods add a lot of saplings
=> Making glue from any sapling

mesecons_materials/init.lua
Ability to produce silicon either from "normal" sand or from desert sand.
=> Silicon production from normal and desert sand

mesecons_compatibility/init.lua
Fix doors texture names due to recent changes to minetest_game.
Fixes https://github.com/Jeija/minetest-mod-mesecons/issues/204
Sorry for all the crazyness :) with the pull requests.
=> Fix doors texture names

mesecons_lightstone/depends.txt, mesecons_lightstone/init.lua
Currently it is much more expensive to make a yellow lightstone compared to a grey one. This pull request serves to balance these recipes and imo makes more sense.
=> Use dye for lightstone recipes - for balance

mesecons_mvps/init.lua
Solves part of #203. I'm not sure if Jeija wants to add support for protection mod so I left it out.
=> Register chests and bookshelves as stoppers

mesecons_extrawires/crossover.lua, mesecons_extrawires/tjunction.lua
=> Remove insulated t-junction and crossover from craftable group

mesecons_mvps/init.lua
This was suggested here:
https://github.com/Jeija/minetest-mod-mesecons/pull/216
=> Register only locked nodes as stoppers

mesecons_luacontroller/init.lua
The associated documentation is at https://github.com/Jeija/mesecons.net/pull/10
=> Add os.datetable(), a (very) limited wrapper for os.date(). Fixes #246.

mesecons_random/init.lua
=> fixed missing capital letter @ line 29

mesecons_random/init.lua
=> Fix active ghoststones drop as item when falling nodes fall into them

mesecons_button/init.lua
=> fix unloaded active button staying on for ever

mesecons_mvps/init.lua
=> do not stop node_timers on mvps move

mesecons_microcontroller/init.lua
I made my own PR for this now.
Fixes #339, closes #353 and closes #351.
Look to "Files changed".
=> add conversation recipes for lua- and microcontroller

mesecons_wires/init.lua
=> prevent wires from being rotated

mesecons/services.lua
=> do not override effector param2 on place

mesecons_random/init.lua
=> make removestone check nodes above for falling

mesecons_mvps/init.lua
~~The falling object is pushed after spawning by current pistons and movestones. Is that bad?~~
=> check for falling on mvps_move

mesecons_movestones/init.lua, mesecons_mvps/init.lua, mesecons_pistons/init.lua
=> mvps: pull objects

mesecons_luacontroller/init.lua
=> [WIP] Close vulnerability and optimize digiline_send

mesecons_luacontroller/init.lua
=> Fix crash when error()ing an invalid value

mesecons_receiver/init.lua
Fix #414.
Dunno how could that code work in MT 0.4.
@beyondlimits
=> Fix mesecon receiver duplication.

mesecons_movestones/init.lua
=> Let things fall behind movestones

settingtypes.txt
Add 'settingtypes.txt' file for configuring mod from client GUI.
=> Add 'settingtypes.txt'

mesecons_luacontroller/init.lua
=> Fix print() exposed to the Luacontroller

mesecons_extrawires/corner.lua, mesecons_extrawires/crossover.lua, mesecons_extrawires/tjunction.lua, mesecons_insulated/init.lua
=> Fix insulated wires selection box

mesecons_movestones/init.lua
=> Fix vertical movestone textures

mesecons_mvps/init.lua
=> Don’t damage unloaded blocks

mesecons_microcontroller/init.lua
Add check nil var with bug from crash server.
=> Fix from microacontroller

mesecons_pistons/init.lua
=> Make sticky piston stick falling things as well

modpack.conf, modpack.txt
=> Use "modpack.conf" and remove "modpack.txt"

mesecons_movestones/init.lua, mesecons_mvps/init.lua, mesecons_pistons/init.lua, settingtypes.txt
Fix #281 
Seems to work well, testing needed. @LoneWolfHT @DS-Minetest
=> Respect protection in MVPS

mesecons_commandblock/init.lua, mesecons_detector/init.lua, mesecons_pressureplates/init.lua
=> Replace deprecated getpos() calls

mesecons_commandblock/init.lua
see https://github.com/minetest-mods/mesecons/issues/552 for details, this also closes it
=> make /tell need shout priv

mesecons_extrawires/vertical.lua, mesecons_insulated/init.lua, mesecons_wires/init.lua
This PR solves https://github.com/minetest/minetest_game/issues/2843.
=> Compatibility with mtg_craft_guide

mesecons/internal.lua
This is a possible solution to https://github.com/minetest-mods/mesecons/issues/571. It implements what I suggested in the description of that issue. These changes seem not to break anything judging by my testing of some of the circuits from the game Mesecons Lab. If some kind of test suite is available, it would be good to run these changes by that.
This patch may slow things down due to reducing the caching, but I haven't done a rigorous benchmark. I didn't notice any big performance changes. Again, is there some benchmark suite available?
=> Only skip conductors with flat rules in turnon/off

mesecons_wires/init.lua
Fixes https://github.com/minetest-mods/mesecons/issues/611
=> Fix mesecon cooking recipes

mesecons_microcontroller/init.lua
particularly in a non-sandboxed environment.
fixes #619.
i'm far from certain these two cases are the only place this is done, but it's a start.
=> microcontroller: fix unsafe pattern usage

mesecons_hydroturbine/init.lua
=> fix typo in hydroturbine recipe

mesecons_extrawires/corner.lua
=> Straighten wire

mesecons/locale/mesecons.de.tr, mesecons_blinkyplant/locale/mesecons_blinkyplant.de.tr, mesecons_button/locale/mesecons_button.de.tr, mesecons_commandblock/locale/mesecons_commandblock.de.tr, mesecons_delayer/locale/mesecons_delayer.de.tr, mesecons_detector/locale/mesecons_detector.de.tr, mesecons_extrawires/locale/mesecons_extrawires.de.tr, mesecons_fpga/locale/mesecons_fpga.de.tr, mesecons_hydroturbine/locale/mesecons_hydroturbine.de.tr, mesecons_insulated/locale/mesecons_insulated.de.tr, mesecons_lamp/locale/mesecons_lamp.de.tr, mesecons_lightstone/locale/mesecons_lightstone.de.tr, mesecons_luacontroller/locale/mesecons_luacontroller.de.tr, mesecons_materials/locale/mesecons_materials.de.tr, mesecons_microcontroller/locale/mesecons_microcontroller.de.tr, mesecons_movestones/locale/mesecons_movestones.de.tr, mesecons_noteblock/locale/mesecons_noteblock.de.tr, mesecons_pistons/locale/mesecons_pistons.de.tr, mesecons_powerplant/locale/mesecons_powerplant.de.tr, mesecons_pressureplates/locale/mesecons_pressureplates.de.tr, mesecons_random/locale/mesecons_random.de.tr, mesecons_solarpanel/locale/mesecons_solarpanel.de.tr, mesecons_stickyblocks/locale/mesecons_stickyblocks.de.tr, mesecons_switch/locale/mesecons_switch.de.tr, mesecons_torch/locale/mesecons_torch.de.tr, mesecons_walllever/locale/mesecons_walllever.de.tr, mesecons_wires/locale/mesecons_wires.de.tr
This translate the Mesecons modpack into German.
=> Translate Mesecons to German

mesecons_detector/init.lua
=> node_detector now accepts a comma-seperated list of nodes like object_detector
