minetest-mods/mesecons

mesecons/oldwires.lua, mesecons_button/init.lua, mesecons_lamp/init.lua, mesecons_lightstone/init.lua, mesecons_powerplant/init.lua, mesecons_torch/init.lua
The LIGHT_MAX global is created in the legacy.lua file in the default
mod; it states that it's there for backwards compatibility, but it would
be better to reference the proper value inside the default table.
=> Don't refer to LIGHT_MAX global; use default.

mesecons_button/init.lua, mesecons_switch/init.lua, mesecons_walllever/init.lua
The left mouse button is used to press button and change state of switch and lever while the same button is used to dig nodes, which makes bad composition especially when we want to pickup levers and button without firing them. However, the right button isn't used for anything. Why not to use it then?
=> Use right mouse button instead of left to press button and change state of switch and lever.

mesecons_detector/init.lua
There were two after_place_nodes which did the same, l think.
l also think about caching the playerdetector positions and stati and using a globalstep.
=> playerdetector: short code and don't get scanname for every object

mesecons_commandblock/init.lua
This solves the issue with command blocks with commands containing characters like ; being uneditable.
=> Escape command block commands for formspec

mesecons_luacontroller/init.lua
I think these two comment lines are left over from when the LuaController did some string scanning to look for forbidden text. It no longer does this, relying entirely on the debug subsystem to prevent taking too much time.
=> Remove an obsolete comment.

mesecons/init.lua, mesecons/internal.lua, mesecons/util.lua
This is a proof of concept of my simplest proposal on GH-277, using the VoxelManipulator to prime the mapblock cache when `get_node_or_nil` fails rather than using forceloading to keep all needed mapblocks in cache at all times.
=> Use a VoxelManipulator to load unloaded areas

mesecons/util.lua
The unhash_blockpos function used to be used in util.lua, but now it is only used in legacy.lua. The one in util.lua can be deleted.
=> Remove an unused function.

mesecons_mvps/init.lua
Objects with big collision boxes are moved.
Objects in stack are moved, not only at front. Ergo fixes #361.
~~Objects lying on top of the nodestack aren't moved anymore. Bad?~~ Edit: fixed.
=> mvps: improve object move

mesecons_pistons/init.lua
If a falling node lied on the pusher, it will fall.
According to @Wuzzy2 also fixes #389.
=> check for falling after piston pusher removal

mesecons_detector/init.lua
As of now, users who disable mesecons_luacontroller do not have an option to craft node or object detectors. Add check.
=> Craft fallbacks for detectors without luacontroller enabled

mesecons_luacontroller/init.lua
EDIT: Fixes, post-rebase:
1. Lack of 'safe' on minetest.deserialize usage
2. String sandbox bypass via (""):evil()
3. Loss of upcoming digilines messages on server shutdown
4. LCs failing to show information on some errors
5. Interrupt IDs as infinite data storage
With any luck something hasn't been broken this time.
=> Hopefully fix LuaController security in a way that doesn't break compat. (NOTE: Conflicts with #379.)

mesecons_extrawires/corner.lua, mesecons_extrawires/depends.txt, mesecons_extrawires/tjunction.lua, mesecons_insulated/depends.txt, mesecons_insulated/init.lua
=> use rotate_simple for insulated wires

mesecons/settings.lua
- 'setting_get' with 'settings:get'
- 'setting_getbool' with 'settings:get_bool'
May not want to merge this until after 0.4.16 release, as the new ['settings' object calls][l_settings] are not available in 0.4.15.
[l_settings]: https://github.com/minetest/minetest/blob/43d1f375d18a2fbc547a9b4f23d1354d645856ca/src/script/lua_api/l_settings.cpp#L267
=> Replace deprecated methods:

mesecons_delayer/init.lua, mesecons_extrawires/corner.lua, mesecons_extrawires/crossover.lua, mesecons_extrawires/tjunction.lua, mesecons_extrawires/vertical.lua, mesecons_hydroturbine/init.lua, mesecons_insulated/init.lua, mesecons_pistons/init.lua, mesecons_pressureplates/init.lua, mesecons_receiver/init.lua, mesecons_torch/init.lua, mesecons_wires/init.lua
This adds the missing sound effects of all nodes which didn't make any sounds. Completion has been verified by `qa_block`.
The incorrect sounds of pressure plates have also been fixed. They now sound like wood and stone instead of leaves. Also, I replaced the `snappy` group with `choppy` and `cracky`.
Fixes #399.
=> Add missing sound effects and fix wrong pressure plate sounds

mesecons_luacontroller/init.lua
If LuaControllers handle sensitive information, hacked clients could get this information from the LuaController. Marking the memory as private fixes this and saves a small amount of bandwidth.
=> Mark LuaController memory as private

mesecons_luacontroller/init.lua
Fix #443.
Order changing alone would be enough, but the message would be covered by the button then.
=> Prevent long error message from covering the button

mesecons_luacontroller/init.lua, settingtypes.txt
Adds optional nodetimer based luacontroller interrupts, useful for server owners, disabled by default:
Original idea by Joe7575 (https://forum.minetest.net/memberlist.php?mode=viewprofile&u=21063)
Settings:
```
mesecon.luacontroller_nodetimer = true
```
=> Luacontroller nodetimer

mesecons_mvps/init.lua
Remove an annoying error message.
I think, it's time to think about compatibility to older minetest versions.
As minetest 5.0 is released, sooner or later everyone will use the new version to be able to connect to the majority of the servers. This means that there won't be anyone who would benefit from the compatibility with older versions.
I suggest:
1. For the next few months keep compatibility with 0.4.17.1, not to older versions.
2. Make a release or a tag or something the like.
3. Only keep compatibility with 5.0+.
4. **Profit** from easier to maintain and less warnings screaming code.
=> Revert "Update init.lua" (getpos->get_pos)

mesecons_detector/doc/nodedetector/description.html, mesecons_detector/init.lua
This adds a table-based digiline API to the node detector:
```lua
{
command = "distance",
distance = 5
}
```
to set distance to 5 (strings also work),
```lua
{
command = "get"
}
```
to get node name, and
```lua
{
command = "scanname",
name = "default:acacia_wood"
}
```
to scan for acacia wood planks. Sending "GET" is identical to `{command = "get"}` and sending "default:acacia_wood" is identical to `{command = "scanname", name = "default:acacia_wood"}`, so this is compatible with existing machines. The novelty is the command to set distance.
=> Add digiline command to set node detector distance

mesecons/util.lua
`mesecons.tablecopy` didn’t support recursive tables, while Minetest `table.copy` works well for them.
~~Fixes~~ #473
=> Use table.copy in mesecons.tablecopy

mesecons_mvps/init.lua
The default value of mvps_protection_mode differs in the settingtypes file and in the code. According to the PR for that feature, the default should be "compat", so I've changed the code so that it is "compat".
=> set mvps_protection_mode default to the documented value

mesecons_fpga/init.lua, mesecons_fpga/logic.lua, mesecons_fpga/tool.lua
1) Unified operands table to remove duplicated code
2) Detach the formspec to use non-node-bound formspecs
* The formspec is quite big: 56 dropdown elements
* Gives the FPGA program serialization more importance - almost no other metadata left over
1) The formspec only closes when it was programmed successfully
*  Is an exit button wanted?
2) Protection checks
=> FPGA: Various code changes

mesecons/actionqueue.lua
The actionqueue does some pretty bad stuff at the moment.
Eg. it takes finds the action with the highest priority (O(n)) for each action in `action_now` (=\> O(n²)) in every globalstep. This is replaced by a table.sort (with a comparator that should make the sort stable).
The goal of this PR is to increase the performance of the actionqueue, to modernize the code and to increase the readability while at the same time not changing the behaviour of anything.
It's very possible that there are other improvements left to do, but such changes might threaten the compatibility.
For testing, my [meseconometer](https://github.com/DS-Minetest/meseconometer) mod might be useful.
Also note that split view might make reviewing easier as some of the diffs are just renaming, movement of code or …
=> Refactor actionqueue.lua

mesecons_mvps/init.lua
This causes the object position checking to only have to check a subset of objects that are near the nodes being moved instead of iterating over every single object on the entire server.
Speedup seems to be most dramatic on servers with large numbers of entities - with about 3000 of them (this is rather common on servers using mods like signs_lib) a single piston push was taking up to 150ms before and is closer to 1-5ms at most now. The effects of this are quite noticeable when building machines using large numbers of pistons.
As far as I can tell, the behavior regarding when objects are moved remains exactly the same, including the bug that @benrob0329 loves so much. If anyone can find a situation where this PR *does* change behavior (aside from speed) then I'd love to hear about it, but …
=> Speed up search for objects to be moved in MVPS

mesecons_button/init.lua, mesecons_doors/init.lua, mesecons_fpga/tool.lua, mesecons_movestones/init.lua, mesecons_noteblock/init.lua, mesecons_pistons/init.lua, mesecons_switch/init.lua, mesecons_walllever/init.lua
The handles were leaked and never used. (The `ephemeral` parameter is available since minetest/minetest@ace3c76112a839aaad34f4343cd924412310bbd3)
=> Make sounds ephemeral

mesecons_noteblock/doc/noteblock/description.html, mesecons_noteblock/init.lua
This PR enables more nodes to trigger the special noteblock sounds:
* Hi-hat: Also accepts obsidian glass instead of only glass
* Snare: Also accepts locked chest instead of only chest
* Kick: Now accepts `group:stone` instead of only `default:stone`
* Crash: Now accepts `group:tree` instead of only `default:tree`
* Lite crash: Now accepts `group:wood` instead of only `default:wood`
=> Make more nodes trigger special noteblock sounds

mesecons_commandblock/init.lua
=> Allow admins (with `protection_bypass` privilege) digging any command block

mesecons_noteblock/init.lua
The fire sound of the note block (when the note block was above a Lava Source) ended too apruptly for my taste. So I added a fade-out of the fire sound.
=> Note Block: Fade out fire sound

mesecons_doors/init.lua, mesecons_doors/mod.conf
Meseconify `xpanes:door_steel_bar` and `xpanes:trapdoor_steel_bar` from MTG (if `xpanes` is present)
=> mesecons_doors: Add MTG steel bar door and trapdoor

mesecons/util.lua, mesecons_luacontroller/init.lua
Fix #473.
This ensures the interrupt ID, if it is a table, is a proper tree. A DAG wouldn’t crash the server either but checking for that is tricky.
This also deprecates non-string IIDs to allow future simplifications. Interrupt ID isn’t a place to store tables.
=> Fix crash on recursive interrupt ID

mesecons/internal.lua, mesecons/presets.lua, mesecons/util.lua, mesecons_extrawires/mesewire.lua
Fix #483.
The two `mergetable` use cases were in fact unrelated, so now there are two functions. The original `mergetable` is now deprecated. ~So, are there any standard ways to track and report its uses?~
=> Replace mesecon.mergetable

mesecons_extrawires/corner.lua
To avoid warning message at load time.
=> Remove undeclared global variable corner_nodebox

mesecons/internal.lua
Fixes #559.
In #556 I've removed a loop in `mesecon.turnoff` and totally forgot that it is very possible that there is no rule to the pos at all (when the receptor doesn't recept to that position) which results in the loop not getting executed even once. This resulted in on-state receptors recepting to any rules.
```
P
D
XWW
or
>
B
W
X
P = powerplant
D = OR gate
W = wire
X = see below
> = NOT gate
B = mese block
```
Place a powerplant at X and dig it, and see if the wire goes off again.
=> Fix on-state receptors (eg. gates) recepting to everywhere

mesecons_button/init.lua, mesecons_delayer/init.lua, mesecons_hydroturbine/init.lua, mesecons_lamp/init.lua
Use everywhere `"opaque"`, but `"clip"` for `hydro_turbine_on` (tested, of course).
=> Fix use_texture_alpha warnings

mesecons/services.lua
When testing this, I put this line at the beginning of `mesecon.turnon` to track calls to it:
```lua
minetest.chat_send_all(minetest.pos_to_string(pos) .. " " .. minetest.pos_to_string(link))
```
Then I placed a switch, turned it on, placed a regular wire adjacent to it, and turned the switch off and on again. With this PR, both calls to `turnon` output the same debugging information. Without it, the values of `link` are opposite to each other.
In other words, this PR makes the behavior when placing a conductor consistent with the behavior when turning on a receptor, with respect to the turned-on conductor.
I don't think the bug occurs with any built-in conductors, but it affects a mod I'm working on.
=> Fix conductor turnon link direction within on_placenode

mesecons/util.lua
The binary state is not padded with zeroes, so they must be inferred.
To test this, I added some custom node definitions to the end of `mesecons/init.lua`:
```lua                                 
local test_states = {"mesecons:t_off", "mesecons:t_001", "mesecons:t_010", "mesecons:t_011", "mesecons:t_100", "mesecons:t_101", "mesecons:t_110", "mesecons:t_on"}
for _, state in ipairs(test_states) do                                          
minetest.register_node(state, {                                         
description = "Test node",                                      
mesecons = {conductor = {                                       
states = test_states,                                   
rules = {                                               
{ …
```
=> Handle getting out-of-bounds bits in get_bit

mesecons/internal.lua, mesecons/util.lua
Most calls to `VoxelManip:write_to_map` made from `turnon` and `turnoff` do not need to include a light update, since most conductors do not change their lighting characteristics depending on their state. There are exceptions, including mese blocks and ghoststone blocks. Such exceptions are automatically handled in this PR. Most unnecessary light updates have been removed.
My changes create a measurable performance improvement. To measure them, I made this change to `mesecons/actionqueue.lua`:
```patch
diff --git a/mesecons/actionqueue.lua b/mesecons/actionqueue.lua
index 5508095..1ccddd5 100644
--- a/mesecons/actionqueue.lua
+++ b/mesecons/actionqueue.lua
@@ -70,6 +70,8 @@ end
-- However, even that does not work in some cases, that's why we delay the time the globalsteps
-- start to be …
```
=> Optimize light updates when turning conductors on and off

mesecons_torch/init.lua
Fixes #580.
The extra rule is probably there to allow using conductors on top of the node that the torch is placed to:
But this rule should not be used for vertical torches.
Test by placing torches.
=> Fix torch rules

mesecons/internal.lua, mesecons/util.lua
This fixes a theoretical issue with my last #578. This issue has to do with aliases. If one of the states listed in the conductor configuration is actually an alias, light updates may not work correctly. This is because the code does not get that the alias refers to the same node definition as the real node name. To amend this, the code now decides whether to update lighting based on the names of nodes that actually exist on the map, not states being changed to. These node names can never be aliases.
This PR simplifies the API of `swap_node_force`. Instead of providing a function, you provide a boolean directly. This is technically backward-compatible; it isn't an API violation to update the lighting when doing so is not required.
I ran the benchmarks provided in #578 and noticed no …
=> Fix conductor lighting when aliases are used

mesecons_mvps/init.lua, mesecons_pistons/init.lua
The other calls to `mvps_process_stack` in mesecons_pistons seem to have been removed before this.
I also removed the body of `mvps_process_stack` itself, as calling it is always redundant. The function still exists, but it does nothing. It is kept in case any external mods are using that part of the API.
This may improve the performance of piston pushing a bit.
=> Basically remove mvps_process_stack

mesecons/util.lua
Sorry, I realized my PR https://github.com/minetest-mods/mesecons/pull/578 had another bug. It can cause things like this:
You can see that the light cuts off sharply. To replicate this yourself, set the powered mese block light source to 14, then make a wire where regular conductors follow a mese block. The regular conductors should extend to the next mapblock. When the wire is powered such that the mese block is powered first, you will see an affect like that in the picture.
To fix this, I made it so that any conductor that needs a light update will make all VMs in the transaction use light updates. This PR should not cause any performance degradation on the fast path. I have not noticed any.
When testing, I recommend applying the following patch to make sure light updates are only used …
=> Fix VM light update issue

mesecons/mod.conf, mesecons_blinkyplant/mod.conf, mesecons_button/mod.conf, mesecons_commandblock/mod.conf, mesecons_delayer/mod.conf, mesecons_detector/mod.conf, mesecons_fpga/mod.conf, mesecons_gates/mod.conf, mesecons_hydroturbine/mod.conf, mesecons_insulated/mod.conf, mesecons_lamp/mod.conf, mesecons_lightstone/mod.conf, mesecons_luacontroller/mod.conf, mesecons_materials/mod.conf, mesecons_microcontroller/mod.conf, mesecons_movestones/mod.conf, mesecons_noteblock/mod.conf, mesecons_pistons/mod.conf, mesecons_powerplant/mod.conf, mesecons_pressureplates/mod.conf, mesecons_random/mod.conf, mesecons_receiver/mod.conf, mesecons_solarpanel/mod.conf, mesecons_stickyblocks/mod.conf, mesecons_switch/mod.conf, mesecons_torch/mod.conf, mesecons_walllever/mod.conf, mesecons_wires/mod.conf
It was not needed. It is now an optional dependency, so that mods which expect to gain default as a transitive dependency by depending on mesecons won't break. However, default has been added as a direct dependency where appropriate within the modpack.
=> Move default dependency to individual mods that need it

mesecons_fpga/init.lua, mesecons_luacontroller/init.lua, mesecons_microcontroller/init.lua
Fixes https://github.com/minetest-mods/mesecons/issues/569.
These devices now only run their code when `action_change` actually changes the state of a port.
I have tested this with circuits from Mesecons Lab.
@Makefile-dot-in, does this fix your issue?
=> Prevent extra pin events with luacontrollers, microcontrollers, and FPGAs

mesecons_doors/init.lua
Trivial.
If you installed luacheck using luarocks, you might have to upgrade it. Using `install` again worked for me.
=> Fix error prone negation reported by luacheck

mesecons/internal.lua, mesecons_mvps/init.lua
The queue implementation is shared with `turnon` and `turnoff`.
The new implementation should be more efficient as it does not do a linear search through the list of nodes for every new node added in order to find duplicates.
=> Use FIFO queue for mvps

mesecons/services.lua, mesecons/util.lua, mesecons_extrawires/corner.lua, mesecons_extrawires/doublecorner.lua, mesecons_extrawires/mod.conf, mesecons_extrawires/tjunction.lua, mesecons_gates/init.lua, mesecons_insulated/init.lua, mesecons_insulated/mod.conf, mesecons_mvps/init.lua, mesecons_receiver/init.lua
Fixes:
- Gates, conductors, and buttonlike components (e.g. buttons) now update things correctly when rotating (fixes #517.)
- Conductors that are turned on do not become stuck in this state when pushed by pistons (they update correctly.)
I did various tests, which you can download as WorldEdit schematics:
- [ex-recv-horiz.we.gz](https://github.com/minetest-mods/mesecons/files/7954363/ex-recv-horiz.we.gz): The wires should not get into the wrong state as you rotate the lever node around its axis.
- [ex-recv-vert.we.gz](https://github.com/minetest-mods/mesecons/files/7954364/ex-recv-vert.we.gz): The wires should not get into the wrong state as you rotate the button node around its axis.
- [ex-rot-and.we.gz](https://github.com/minetest-mods/mesecons/files/7954365/ex-rot-and.we.gz): The …
=> Make some fixes to movement and rotation

mesecons/util.lua, mesecons_delayer/init.lua, mesecons_extrawires/corner.lua, mesecons_extrawires/doublecorner.lua, mesecons_extrawires/tjunction.lua, mesecons_gates/init.lua, mesecons_insulated/init.lua, mesecons_receiver/init.lua
There are several different components that can be rotated around the Y axis. This PR consolidates all their rules getter functions using a new API function. This has the added benefit of making them all use lookup tables instead of repeated rotation, which is probably faster and creates less garbage. I think I have noticed a minor performance increase.
I have tested that the affected nodes still work, but it would be good if someone could verify this.
=> Consolidate horizontal rules getters

mesecons_luacontroller/init.lua
Saw a fatal error recently when the virtual ports didn't exist for some reason...
```
2022-06-08 00:23:19: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'mesecons_luacontroller' in callback environment_Step(): ...bls/bin/../mods/mesecons/mesecons_luacontroller/init.lua:472: bad argument #1 to 'pairs' (table expected, got nil)
2022-06-08 00:23:19: ERROR[Main]: stack traceback:
2022-06-08 00:23:19: ERROR[Main]:     [C]: in function 'pairs'
2022-06-08 00:23:19: ERROR[Main]:     ...bls/bin/../mods/mesecons/mesecons_luacontroller/init.lua:472: in function 'create_environment'
2022-06-08 00:23:19: ERROR[Main]:     ...bls/bin/../mods/mesecons/mesecons_luacontroller/init.lua:627: in function 'run_inner'
2022-06-08 00:23:19: ERROR[Main]: …
```
=> Exit with error if vports do not exist for any reason

mesecons_gates/init.lua
All logic gates have paramtype2 = "facedir". The upper three bits of param2 are therefore unused. However, instead of using these bits to store inputs, binary logic gates store their inputs in metadata, using more than 14 extra bytes of storage per logic gate node. This PR aims to change that in a backward-compatible way.
When a binary logic gate is updated, bit 5 of its param2 is checked. Bit 5 being set to 1 indicates that the logic gate is using the new implementation. In this case, bit 6 is the value of input1 and bit 7 is the value of input2. If bit 5 is 0, then the logic gate is either old or has just been placed. In this case, the binary logic gate gets migrated to the new implementation. Bit 5 is then set and the metadata is cleared if it is present.
I decided not to use LBMs to …
=> Store gate inputs in param2 instead of metadata

mesecons/presets.lua
Fixes https://github.com/minetest-mods/mesecons/issues/610.
To test, load up devtest with Mesecons and homedecor_lighting. Place a Mesecons lever and, separately, a `homedecor:glowlight_small_cube_14`. Use the param2 tool to set the lever's param2 to 25 and the light's param2 to 6. Try turning on the lever. Then try turning on the light using a switch adjacent to it. The game should not crash.
=> Handle invalid param2 in presets.lua

mesecons/init.lua, mesecons/internal.lua, mesecons_mvps/spec/node_spec.lua
This is a less disruptive alternative to https://github.com/minetest-mods/mesecons/pull/594. See that PR for how to reproduce the issue. This one just checks that effectors should actually be powered off when they are powered directly by a receptor. When a receptor turns off conductors instead, this check is effectively done already.
A call to `changesignal` was removed in `mesecons/init.lua`. I think this was superfluous, as it was first added in 841bc70b97e237477b0dd9ba36fd9cd307daf581 to fix a bug that does not exist in the current code.
=> Fix mvps receptor_off issue

mesecons_fpga/spec/helper_spec.lua, mesecons_fpga/tool.lua
The new code is equivalent. It has the added benefit of allowing some tests to be enabled.
To test, just try out the FPGA tool. Also make sure that tools whose metadata was set before the update still work.
=> Avoid deprecated item metadata accessors

mesecons/init.lua
I don't think it's important to print that the mod loading succeeded. Other mods also do not print a message when loading.
=> Do not print the mesecons OK message

mesecons_luacontroller/init.lua, settingtypes.txt
fixes #626.
default behavior is now to dump and log the argument to print similar to how it used to work. by setting `mesecon.luacontroller_print_behavior = noop` in minetest.conf, this behavior can be disabled.
=> add option to disable printing inside a luacontroller

mesecons_pressureplates/init.lua
This PR makes pressure plates check to see if the collisionbox of an entity intersects with the pressure plate. I originally put this in MineClone2.
Without the PR an entity did not need to contact the pressure plate to trigger it. Also some entities associated with nodes would trigger it if the node is next to the pressure plate.
One possible issue is that large entites or entites with the origin point not in the feet can't be detected. This can be simply fixed by increasing the radius passed to minetest.get_objects_inside_radius().
Players, mobs, dropped items, etcetera are supported. Those were all supported before but I just want to establish the facts.
I tested in MT 5.0.1 and MT 5.6.
=> Pressure plates check for entity contact

mesecons_mvps/init.lua
Fixes #544.
For testing please note that if you've already pushed out of world, there's air now, so you'll have to move your test piston.
=> Mvps: make mvps stoppers non-replaceable even if they are buildable_to

mesecons_luacontroller/init.lua
Adds the default minetest string.split function.
I know it's just one helper function but it were also asked in #470 and should be pretty safe.
A player could anyway add it to his controller:
``` Lua
--  Copied from mt code: https://github.com/minetest/minetest/blob/0df646e0689b5324c7bdb13205c2a63e42ebe8e8/builtin/common/misc_helpers.lua#L169
function string.split(str, delim, include_empty, max_splits, sep_is_pattern)
delim = delim or ","
max_splits = max_splits or -2
local items = {}
local pos, len = 1, #str
local plain = not sep_is_pattern
max_splits = max_splits + 1
repeat
local np, npe = string.find(str, delim, pos, plain)
np, npe = (np or (len+1)), (npe or (len+1))
if (not np) or (max_splits == 1) then
np = len + 1
npe = np
end
local s = string.sub(str, pos, np - 1)
if include_empty …
```
=> Add string.split function

mesecons/internal.lua, mesecons_extrawires/vertical.lua, mesecons_mvps/init.lua, mesecons_wires/init.lua
Less spectacular deduplication. Depending on the Lua internals, this might also improve the performance a bit. The main goal is however to reduce repetitive code, which makes it difficult to spot differences - or bugs for that matter.
How to test:
1. Sticky piston, connected with regular and vertical wires
2. Turn the piston (and wires) on and off
Or see whether the tests pass...
=> Reduce redundancy in minetest.registered_nodes lookups

mesecons_delayer/init.lua
Fixes #656
i believe the cause of this bug is a chain of events as such:
* delayer receives effector_on, and starts a timer
* delayer receives effector_off, however the node has not been updated somehow (perhaps due to caching somewhere), and thus this is dropped
* delayer swaps node into on state
this may be caused by an underlying bug somewhere in the action queue, but simply changing the unpowered state so it also responds to power off events seems to do the trick just fine.
=> fix 1-tick pulses causing delayers to get stuck in the on state

mesecons_luacontroller/init.lua
NaN can cause problems (and crashes) if the receiving node doesn't check for it, this PR makes it so NaN values are removed from digiline messages.
=> Remove NaN values from digiline messages

mesecons_doors/init.lua
The main code quality improvement here is the functionalization of code: now trapdoors are also overriden using their own function, and both `meseconify_door` and `meseconify_trapdoor` are now ran inside for loops with local lists of base node names. In the future, this could help refactor this mod entirely to not list doors manually but parse through the doors.registered_* variables, ensuring that every door works.
As a nice bonus, [Voxelgarden](https://codeberg.org/voxelgarden/voxelgarden) support is fixed, and potentially so is support for other games with exotic implementations of the doors mod. No longer are we assuming that the existence of `doors.get` means that all the trapdoors exist too; now, if the meseconify function doesn't find their definition, it just returns without …
=> [mesecons_doors] Improve code quality and fix Voxelgarden support

mesecons_detector/init.lua
This PR fixes a fatal error: if a malformed digiline table is passed into a node detector, the server may crash because of a mismatched data type.
For example, this weird backtrace happened because technic is sending "malformed" tables:
```
ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod '??' in callback node_on_timer(): $HOME/.minetest/mods/mesecons/mesecons_detector/init.lua:63: bad argument #2 to 'set_string' (string expected, got table)
ERROR[Main]: stack traceback:
ERROR[Main]:       [C]: in function 'set_string'
ERROR[Main]:       $HOME/.minetest/mods/mesecons/mesecons_detector/init.lua:63: in function 'action'
ERROR[Main]:       $HOME/.minetest/mods/digicontrol/override.lua:45: in function 'transmit'
ERROR[Main]: …
```
=> Check for digiline message field type

mesecons/locale/mesecons.fr.tr, mesecons_blinkyplant/locale/mesecons_blinkyplant.fr.tr, mesecons_button/locale/mesecons_button.fr.tr, mesecons_commandblock/locale/mesecons_commandblock.fr.tr, mesecons_delayer/locale/mesecons_delayer.fr.tr, mesecons_delayer/locale/template.txt, mesecons_detector/locale/mesecons_detector.fr.tr, mesecons_extrawires/locale/mesecons_extrawires.fr.tr, mesecons_fpga/locale/mesecons_fpga.fr.tr, mesecons_hydroturbine/locale/mesecons_hydroturbine.fr.tr, mesecons_insulated/locale/mesecons_insulated.fr.tr, mesecons_lamp/locale/mesecons_lamp.fr.tr, mesecons_lightstone/locale/mesecons_lightstone.fr.tr, mesecons_luacontroller/locale/mesecons_luacontroller.fr.tr, mesecons_materials/locale/mesecons_materials.fr.tr, mesecons_microcontroller/locale/mesecons_microcontroller.fr.tr, mesecons_movestones/locale/mesecons_movestone.fr.tr, mesecons_noteblock/locale/mesecons_noteblock.fr.tr, mesecons_pistons/locale/mesecons_pistons.fr.tr, mesecons_powerplant/locale/mesecons_powerplant.fr.tr, mesecons_pressureplates/locale/mesecons_pressureplates.fr.tr, mesecons_random/locale/mesecons_random.fr.tr, mesecons_solarpanel/locale/mesecons_solarpanel.fr.tr, mesecons_stickyblocks/locale/mesecons_stickyblocks.fr.tr, mesecons_switch/locale/mesecons_switch.fr.tr, mesecons_torch/locale/mesecons_torch.fr.tr, mesecons_walllever/locale/mesecons_walllever.fr.tr, mesecons_wires/locale/mesecons_wires.fr.tr
I've just added a French translation. If anyone sees an error, please let me know and I'll try to correct it.
=> Add French translation to Mesecon

mesecons/actionqueue.lua
Currently there is the replacement of existing globalstep function, but it doesn't consider callback origins, therefore, the engine doesn't know what mod is the owner of the new function. The result - there is unknown entry in the profiler output, displayed as `??` modname with `*` instrumentation.
This patch fixes it by setting callback origin of the replaced globalstep function
=> Fix mesecons displayed as unknown(??) mod in the profiler

mesecons_doors/init.lua
Removed hardcoded door names and instead now use the API of the door mod to meseconify all doors and trapdoors that have been registered after the mods are finished loading.
=> Support doors and trapdoors from mods

mesecons_commandblock/init.lua
I think it's not worth the effort to update commandblocks already placed...
=> commandblock: replace deprecated formspec element "invsize"

mesecons_luacontroller/init.lua
This is a simple solution for #689
=> added sha256 function to lua controller

mesecons_commandblock/init.lua, settingtypes.txt
This PR adds a configurable maximum length for chatcommand parameters. Long parameters can possibly be used to cause crashes and other problems since mods don't expect parameters to be very long.
Hopefully the default of 10,000 bytes won't break any existing command blocks.
This issue this PR aims to fix somewhat mitigated by the formspec input length limit and https://github.com/minetest/minetest/commit/9c9309cdbb053598aaf08506928a4824e78b4622 (introduced in 5.7.0), however other mods (like [irc](https://github.com/minetest-mods/irc/pull/53)) don't have a message size limit, though a 10 kB message will probably do just as much harm, server owners would have to configure the limit if they can live with some command blocks no longer working.
=> Limit chatcommand parameter length in command blocks

mesecons_extrawires/vertical.lua, mesecons_receiver/init.lua
Seems like the warnings should be more explicit. They can be overlooked for years...
=> Add missing `use_texture_alpha`

mesecons_detector/init.lua, mesecons_detector/mod.conf
Like in `mesecons_microcontroller` mod.
Some are hesitant to install luacontroller on their servers because of the risk of abuse.
And they don't want to have a broken recipe in craftguide.
=> Make the detector recipe from luacontroller optional

.github/workflows/check.yml
Use GitHub action repo for mineunit tests.
* Should be enough to close #706 
* Tested on fork: https://github.com/S-S-X/mesecons/actions/runs/15518379561
* Provides a bit cleaner workflow definition.
* Should also improves test performance a bit by utilizing pre built containers from https://hub.docker.com/r/mineunit/mineunit
=> Switch to mineunit-actions

.luacheckrc, mesecons_gamecompat/compat_hades.lua, mesecons_gamecompat/init.lua, mesecons_gamecompat/mod.conf
Integrate support for Hades Revisited into the Mesecons modpack, allowing it to tag https://content.luanti.org/packages/SFENCE/hades_mesecons/ as obsolete.
=> Support for Hades Revisited.
